function [uuids, title_line3, uuid_query]=Query_Creation2(conn, signal_filter_string)
    %Retreive List of Materials
    material_query='select distinct material from boeing_db_structure.layers';
    material_query_result=fetch(conn,material_query);
    material_list=table2cell(material_query_result);
    [indx,tf] = listdlg('ListString',material_list,'SelectionMode','single', 'PromptString','Select material:');
    material = string(material_list(indx));
    
    if tf==0
        %nothing was selected. so no filters are applied.
        uuid_query=['select distinct borehole_id from boeing_db_structure.boreholes '...
        'join boeing_db_structure.sensor_deployments on boeing_db_structure.boreholes.experiment=sensor_deployments.experiment '...
        'join boeing_db_structure.sensors on sensor=sensor_id '... 
        signal_filter_string...
        ')'];
        uuids = table2cell(fetch(conn,uuid_query));
        title_line3='No Filters Specified';
        return
    end
    
    %for the chosen material, retreive list of potential tools and ask for
    %further input
    QueryformatSpec = ['select distinct tool_name from boeing_db_structure.boreholes '...
    'join boeing_db_structure.sensor_deployments on boeing_db_structure.boreholes.experiment=sensor_deployments.experiment '...
    'join boeing_db_structure.qualitycards on qualitycards.borehole=borehole_id '...
    'join boeing_db_structure.tools on tools.tool_id=tool '...
    'join boeing_db_structure.layers on qualitycards.layer=layer_id '...
    'join boeing_db_structure.sensors on sensor=sensor_id '... 
    signal_filter_string...
    ') and material=''%s'''];
    tool_query=sprintf(QueryformatSpec, material);
    tool_query_result=fetch(conn,tool_query);
    tool_list = table2cell(tool_query_result);
    
    [indx,tf] = listdlg('ListString',tool_list,'SelectionMode','single', 'PromptString','Select tool:');
    
    if tf==0
        QueryformatSpec=['select distinct borehole_id from boeing_db_structure.boreholes '...
        'join boeing_db_structure.tools on tools.tool_id=tool '...
        'join boeing_db_structure.qualitycards on qualitycards.borehole=borehole_id '...
        'join boeing_db_structure.layers on qualitycards.layer=layer_id '...
        'join boeing_db_structure.sensor_deployments on boeing_db_structure.boreholes.experiment=sensor_deployments.experiment '...
        'join boeing_db_structure.sensors on sensor=sensor_id '... 
        signal_filter_string...
        ') and material=''%s'''];
        uuid_query=sprintf(QueryformatSpec, material);
        uuid_query_result=fetch(conn,uuid_query);
        uuids = table2cell(uuid_query_result);
        title_line3Spec='Material: %s';
        title_line3=sprintf(title_line3Spec, material);
        return
    end
    
    tool_name = string(tool_list(indx));
    
    %Finally Query uuids of boreholes for the chosen material/tool
    %combination
    QueryformatSpec = ['select borehole_id from boeing_db_structure.boreholes '...
    'join boeing_db_structure.sensor_deployments on boeing_db_structure.boreholes.experiment=sensor_deployments.experiment '... 
    'join boeing_db_structure.qualitycards on qualitycards.borehole=borehole_id '... 
    'join boeing_db_structure.tools on tool=tools.tool_id '...
    'join boeing_db_structure.layers on qualitycards.layer=layer_id '...
    'join boeing_db_structure.sensors on sensor=sensor_id '... 
    signal_filter_string...
    ') and material=''%s'' and tool_name =''%s''']; 
    
    uuid_query=sprintf(QueryformatSpec, material, tool_name);
    uuid_query_result=fetch(conn,uuid_query);
    uuids = table2cell(uuid_query_result);
    title_line3Spec='Material: %s, Tool: %s';
    title_line3=sprintf(title_line3Spec, material, tool_name);
