function [uuids, title_line3, uuid_query]=Query_Creation1(conn, signal_filter_string)
    
    choice_list={'coated','not coated'};
    [indx,tf] = listdlg('ListString',choice_list,'SelectionMode','single', 'PromptString','Select material:');
    
    if tf==0
        %nothing was selected. so no filters are applied.
        uuid_query=['select distinct borehole_id from boeing_db_structure.boreholes '...
        'join boeing_db_structure.sensor_deployments on boeing_db_structure.boreholes.experiment=sensor_deployments.experiment '...
        'join boeing_db_structure.sensors on sensor=sensor_id '... 
        signal_filter_string...
        ')'];
        uuids = table2cell(fetch(conn,uuid_query));
        title_line3='No Filters Specified';
        return
    end
    
    %filter is applied.
    uuid_query_formatSpec = ['select distinct borehole_id from boeing_db_structure.boreholes '...
    'join boeing_db_structure.sensor_deployments on boeing_db_structure.boreholes.experiment=sensor_deployments.experiment '... 
    'join boeing_db_structure.qualitycards on qualitycards.borehole=borehole_id '... 
    'join boeing_db_structure.tools on tool=tools.tool_id '...
    'join boeing_db_structure.sensors on sensor=sensor_id '... 
    signal_filter_string...
    ') and coating=''%s'''];
    if indx==1
        uuid_query=sprintf(uuid_query_formatSpec,'True');
        title_line3='Only Coated Drills';
    else
        uuid_query=sprintf(uuid_query_formatSpec,'False');
        title_line3='Only Non-Coated Drills';
    end
    uuids = table2cell(fetch(conn,uuid_query));